apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    storage: nfs
  name: pv-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: giropops
  nfs:
    path: "/opt/sites"
    server: 172.17.0.1
