apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    storage: lento
  name: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/tmp/
  storageClassName: giropops
